services:
  - type: web
    name: linebot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: 2b3e83216a69c25ba3a94db83a5e631d
        sync: false
      - key: ZyXgdJ6lWQoSUFbGn7lKCybo+lRzDxpWvNjRBobYFEMXgnuSXetSELF55G4bB9uxJ5sXCy4ej5sax5+dgHk6tEoszp1G8pWe8gB9BQKBMVJDHrERUz35mcFSBVrA1a/WwfvT7XJvb0cQ9V1PTn+oAwdB04t89/1O/w1cDnyilFU=
        sync: false
